export const USER = Object.freeze({
  FB_LOGIN: 'FB_LOGIN',
  GOOGLE_LOGIN: 'GOOGLE_LOGIN',
})

export const MOVIES = Object.freeze({
  GET_POPULAR: 'GET_POPULAR',
  GET_FAVORITES: 'GET_FAVORITES',
  ADD_FAVORITES: 'ADD_FAVORITES',
  REMOVE_FAVORITES: 'REMOVE_FAVORITES',
})